-- ================================================================
-- 難波商店街地域BCPマップ 初期スキーマ
-- 対象: stores / disaster_events / reports / support_requests
--
-- 【実行手順】
--   Supabase ダッシュボード > SQL Editor > New Query に
--   このファイルの内容を貼り付けて Run を押してください。
--
-- 【注意】
--   - RLS は有効化済みですが、認証実装前の一時的な全許可ポリシーを設定しています。
--     認証実装時に各ポリシーを差し替えてください。
--   - users テーブルへの外部キーは認証実装後に追加します。
--     現在は created_by / reported_by / assigned_to を bigint のみで定義します。
-- ================================================================


-- ================================================================
-- 0. 共通: updated_at 自動更新トリガー関数
-- ================================================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ================================================================
-- 1. stores テーブル
-- ================================================================
CREATE TABLE stores (
  id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         varchar(100) NOT NULL,
  category     varchar(50)  NOT NULL,
  address      varchar(255) NOT NULL,
  latitude     numeric(9,6) NOT NULL,
  longitude    numeric(9,6) NOT NULL,
  area_name    varchar(50)  NOT NULL,
  manager_name varchar(50)  NOT NULL,
  phone        varchar(20)  NOT NULL,
  email        varchar(100) NOT NULL,
  note         text,
  created_at   timestamptz  NOT NULL DEFAULT now(),
  updated_at   timestamptz  NOT NULL DEFAULT now()
);

CREATE TRIGGER set_stores_updated_at
  BEFORE UPDATE ON stores
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

ALTER TABLE stores ENABLE ROW LEVEL SECURITY;
-- 認証実装後にこのポリシーを役割別ポリシーに差し替える
CREATE POLICY "temp_allow_all" ON stores FOR ALL USING (true) WITH CHECK (true);


-- ================================================================
-- 2. disaster_events テーブル
-- ================================================================
CREATE TABLE disaster_events (
  id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        varchar(100) NOT NULL,
  event_type  varchar(50)  NOT NULL,
  target_area varchar(100) NOT NULL,
  started_at  timestamptz  NOT NULL,
  ended_at    timestamptz,
  status      varchar(20)  NOT NULL DEFAULT 'active'
              CHECK (status IN ('active', 'closed', 'training')),
  memo        text,
  created_by  bigint,      -- TODO: 認証実装後に REFERENCES auth.users(id) を追加
  created_at  timestamptz  NOT NULL DEFAULT now(),
  updated_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE TRIGGER set_disaster_events_updated_at
  BEFORE UPDATE ON disaster_events
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

ALTER TABLE disaster_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "temp_allow_all" ON disaster_events FOR ALL USING (true) WITH CHECK (true);


-- ================================================================
-- 3. reports テーブル
-- ================================================================
CREATE TABLE reports (
  id                  bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  disaster_event_id   bigint      NOT NULL REFERENCES disaster_events(id) ON DELETE RESTRICT,
  store_id            bigint      NOT NULL REFERENCES stores(id)          ON DELETE RESTRICT,
  safety_status       varchar(20) NOT NULL DEFAULT 'unknown'
                      CHECK (safety_status IN ('safe', 'damaged', 'checking', 'evacuated', 'unknown')),
  business_status     varchar(20) NOT NULL DEFAULT 'unknown'
                      CHECK (business_status IN ('open', 'partially_open', 'closed', 'preparing', 'checking', 'unknown')),
  has_damage          boolean     NOT NULL DEFAULT false,
  has_support_request boolean     NOT NULL DEFAULT false,
  memo                text,
  is_proxy            boolean     NOT NULL DEFAULT false,
  proxy_method        varchar(100),
  reported_by         bigint,     -- TODO: 認証実装後に REFERENCES auth.users(id) を追加
  reported_at         timestamptz NOT NULL DEFAULT now(),
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),

  -- 同一災害イベントで同一店舗は1報告のみ（重複防止）
  UNIQUE (disaster_event_id, store_id)
);

CREATE TRIGGER set_reports_updated_at
  BEFORE UPDATE ON reports
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "temp_allow_all" ON reports FOR ALL USING (true) WITH CHECK (true);


-- ================================================================
-- 4. support_requests テーブル
-- ================================================================
CREATE TABLE support_requests (
  id                bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  disaster_event_id bigint      NOT NULL REFERENCES disaster_events(id) ON DELETE RESTRICT,
  store_id          bigint      NOT NULL REFERENCES stores(id)          ON DELETE RESTRICT,
  support_type      varchar(30) NOT NULL
                    CHECK (support_type IN (
                      'human_support', 'goods_support', 'cleanup',
                      'facility_check', 'building_check', 'reopen_support', 'other'
                    )),
  urgency           varchar(10) NOT NULL DEFAULT 'middle'
                    CHECK (urgency IN ('high', 'middle', 'low')),
  detail            text,
  status            varchar(20) NOT NULL DEFAULT 'open'
                    CHECK (status IN ('open', 'in_progress', 'closed')),
  assigned_to       bigint,     -- TODO: 認証実装後に REFERENCES auth.users(id) を追加
  created_by        bigint,     -- TODO: 認証実装後に REFERENCES auth.users(id) を追加
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER set_support_requests_updated_at
  BEFORE UPDATE ON support_requests
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

ALTER TABLE support_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "temp_allow_all" ON support_requests FOR ALL USING (true) WITH CHECK (true);


-- ================================================================
-- 5. シードデータ（開発用・モックデータと同一内容）
-- ================================================================

-- stores
INSERT INTO stores (id, name, category, address, latitude, longitude, area_name, manager_name, phone, email) VALUES
  (1,  'たこ焼き本舗 なんば店',   '飲食店',       '大阪府大阪市中央区難波3-1-1', 34.668700, 135.501300, 'A エリア', '山田 太郎', '06-1234-5678', 'takoyaki@namba.jp'),
  (2,  'アパレル NAMBA',          'アパレル',     '大阪府大阪市中央区難波3-1-5', 34.669000, 135.502000, 'A エリア', '鈴木 花子', '06-2345-6789', 'apparel@namba.jp'),
  (3,  'ドラッグストア ケア難波', 'ドラッグストア','大阪府大阪市中央区難波3-2-1', 34.668000, 135.500800, 'A エリア', '佐藤 一郎', '06-3456-7890', 'care@namba.jp'),
  (4,  '土産店 大阪みやげ',       '土産店',       '大阪府大阪市中央区難波3-2-8', 34.669500, 135.503000, 'B エリア', '田中 幸子', '06-4567-8901', 'miyage@namba.jp'),
  (5,  'カフェ ほっと',           '飲食店',       '大阪府大阪市中央区難波4-1-2', 34.667800, 135.504000, 'B エリア', '中村 誠',   '06-5678-9012', 'cafe@namba.jp'),
  (6,  '電器店 エレクトロ難波',   '電器店',       '大阪府大阪市中央区難波4-2-1', 34.670200, 135.501800, 'B エリア', '小林 健太', '06-6789-0123', 'electro@namba.jp'),
  (7,  '書店 なんばブックス',     '書店',         '大阪府大阪市中央区難波4-3-5', 34.671000, 135.502500, 'C エリア', '加藤 美咲', '06-7890-1234', 'books@namba.jp'),
  (8,  '靴店 シューズパラダイス', 'ファッション', '大阪府大阪市中央区難波4-4-2', 34.671500, 135.501000, 'C エリア', '渡辺 隆',   '06-8901-2345', 'shoes@namba.jp'),
  (9,  '居酒屋 大阪の夜',         '飲食店',       '大阪府大阪市中央区難波5-1-3', 34.669800, 135.504500, 'C エリア', '松本 和也', '06-9012-3456', 'izakaya@namba.jp'),
  (10, 'コンビニ ナムバマート',   'コンビニ',     '大阪府大阪市中央区難波5-2-1', 34.667200, 135.502800, 'A エリア', '伊藤 博',   '06-0123-4567', 'conbini@namba.jp'),
  (11, '雑貨店 なんばライフ',     '雑貨',         '大阪府大阪市中央区難波5-3-4', 34.668300, 135.505000, 'B エリア', '清水 久美', '06-1111-2222', 'life@namba.jp'),
  (12, '眼鏡店 ビジョン難波',     '眼鏡',         '大阪府大阪市中央区難波5-4-7', 34.670700, 135.503500, 'C エリア', '橋本 真一', '06-2222-3333', 'vision@namba.jp');

-- identity シーケンスを挿入済み最大値に合わせる
SELECT setval(pg_get_serial_sequence('stores', 'id'), (SELECT MAX(id) FROM stores));

-- disaster_events（訓練用イベント1件）
INSERT INTO disaster_events (id, name, event_type, target_area, started_at, status, memo) VALUES
  (1, '南海トラフ地震（訓練）', '地震', '難波商店街全域', '2026-06-09 09:00:00+09', 'active', '震度6強を想定した訓練モードです');

SELECT setval(pg_get_serial_sequence('disaster_events', 'id'), (SELECT MAX(id) FROM disaster_events));
